<?php

return [
    'setup' => 'Как пользоваться ботом',
    'list' => 'Список обьектов',
    'filter' => 'Найди обьект по фильтру',
    'showall' => 'Посмотри все обьекты',
    'type_house' => 'Дом',
    'type_flat' => 'Квартира',
    'type_both' => 'И то, и другое',
    'city_budva' => 'Будва',
    'city_bar' => 'Бар',
    'city_tivat' => 'Тиват',
    'city_podgorica' => 'Подгорица',
    'city_herzegnovi' => 'Херцег-Нови',
    'city_sutomore' => 'Сутоморе',
    'city_page_2' => 'Страница 2',
    'city_page_1' => 'Страница 1',
    'city_next_stage' => 'Следующий раздел',
    'price_value_1' => '0-100k€',
    'price_value_2' => '100k€-300k€',
    'price_value_3' => '300k€-500k€',
    'price_value_4' => '500k€-∞',
    'price_value_5' => 'Все',
    'price_value_your' => 'Свой диапазон',
];